version: '3.8'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 9091:1972
      - 9092:52773
      - 9093:53773
    volumes:
      - ./:/irisrun/repo